# -*- coding: utf-8 -*-
"""app_fp1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_sAtq4xBlr_i_lSaRrzDMErF6VawGpfT
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import requests

# Replace this with your live ngrok URL (copy from Colab after running ngrok)
FASTAPI_URL = "https://9dfa-34-41-88-204.ngrok-free.app"

st.title("⚡ Energy Consumption Forecast")

sector = st.selectbox("Select Sector", ["Commercial", "Industrial"])
months = st.selectbox("Forecast Period (months)", [3, 6, 9, 12])

if st.button("Predict"):
    with st.spinner("Calling forecasting model..."):
        try:
            response = requests.get(FASTAPI_URL, params={"sector": sector, "months": months})
            result = response.json()

            df = pd.DataFrame({
                "Month +N": [f"Month +{i+1}" for i in range(len(result["forecast"]))],
                "Forecast": result["forecast"],
                "Lower CI": [x[0] for x in result["confidence_interval"]],
                "Upper CI": [x[1] for x in result["confidence_interval"]],
            })

            st.success("Prediction complete!")
            st.dataframe(df)
            st.line_chart(df.set_index("Month +N")[["Forecast", "Lower CI", "Upper CI"]])

        except Exception as e:
            st.error(f"Something went wrong: {e}")
