# -*- coding: utf-8 -*-
"""app_fp1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_sAtq4xBlr_i_lSaRrzDMErF6VawGpfT
"""

import streamlit as st
import requests
import pandas as pd

# Replace with your ngrok URL
FASTAPI_URL = "https://5f7e-35-222-192-220.ngrok-free.app"

st.title("🔮 Electricity Forecast")

if st.button("Predict"):
    try:
        response = requests.get(FASTAPI_URL)
        result = response.json()

        df = pd.DataFrame({
            "Month +N": [f"Month +{i+1}" for i in range(len(result['forecast']))],
            "Forecast": result['forecast'],
            "Lower": [x[0] for x in result['confidence_interval']],
            "Upper": [x[1] for x in result['confidence_interval']]
        })

        st.success("Forecast received:")
        st.dataframe(df)
        st.line_chart(df.set_index("Month +N")[["Forecast", "Lower", "Upper"]])

    except Exception as e:
        st.error(f"Something went wrong: {e}")